-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Room"
(
    room_id character varying(4)[] NOT NULL,
    admin integer NOT NULL,
    name character varying(30) NOT NULL,
    PRIMARY KEY (room_id)
);

CREATE TABLE IF NOT EXISTS public."User"
(
    user_id serial NOT NULL,
    username character varying(30) COLLATE pg_catalog."default" NOT NULL,
    public_key character varying(1000) NOT NULL,
    PRIMARY KEY (user_id),
    UNIQUE (username)
);

COMMENT ON TABLE public."User"
    IS 'The public key is treated as var char because it is too big for int representation';

CREATE TABLE IF NOT EXISTS public."User_In_Room"
(
    room_id integer NOT NULL,
    user_id integer NOT NULL,
    PRIMARY KEY (room_id, user_id)
);

ALTER TABLE IF EXISTS public."Room"
    ADD FOREIGN KEY (admin)
    REFERENCES public."User" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."User_In_Room"
    ADD FOREIGN KEY (room_id)
    REFERENCES public."Room" (room_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."User_In_Room"
    ADD FOREIGN KEY (user_id)
    REFERENCES public."User" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;