-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Room"
(
    room_id serial NOT NULL,
    admin integer NOT NULL,
    CONSTRAINT "Room_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."User"
(
    user_id serial NOT NULL,
    username character varying(30) COLLATE pg_catalog."default" NOT NULL,
    public_key character varying(1000) NOT NULL,
    CONSTRAINT "User_pkey" PRIMARY KEY (id),
    CONSTRAINT unique_username UNIQUE (username)
);

COMMENT ON TABLE public."User"
    IS 'The public key is treated as var char because it is too big for biginteger representation';

CREATE TABLE IF NOT EXISTS public."User_In_Room"
(
    user_in_room_id serial NOT NULL,
    room_id integer NOT NULL,
    user_id integer NOT NULL,
    PRIMARY KEY (user_in_room_id)
);

ALTER TABLE IF EXISTS public."Room"
    ADD CONSTRAINT admin_fkey FOREIGN KEY (admin)
    REFERENCES public."User_In_Room" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."User_In_Room"
    ADD CONSTRAINT user_kfey FOREIGN KEY (user_id)
    REFERENCES public."User" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."User_In_Room"
    ADD CONSTRAINT room_fkey FOREIGN KEY (room_id)
    REFERENCES public."Room" (room_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;